Agilent8163Multimeter:
  address: "GPIB0::20::INSTR"        # GPIB address
  power_slot: 2                      # Slot number for the power
  laser_slot: 1                      # Slot number for the laser
  power_channel: 1                   # Channel number for the power meter
  start_wavelength: 1549.0           # In nm
  stop_wavelength: 1551.0            # In nm
  step: 0.01                         # In nm (user-defined step size)
  delay: 0.1                         # Seconds between steps

Keithley2400:
  address: "GPIB0::24::INSTR"        # GPIB address
  start_voltage: 0.0                 # In Volts
  stop_voltage: 1.5                  # In Volts
  step_voltage: 0.01                 # In Volts
  compliance_current: 0.01           # In Amps (safety limit to protect the device)
  compliance_voltage: 1.0            # In Volts
  resistance_range: 20E3             # In Ohms
  source_voltage_range: 2.0          # In Volts
  measure_current_range: 0.01        # In Amps
  wire_mode: 2                       # 2-wire mode: uses two wires for both sourcing and measuring
  delay: 0.1                         # Seconds between steps


DUT:
  name: "NAME"          # Name of the device under test
  type: "TYPE"             # Type of the device
